image: node

stages:
  - build
  - lint
  - test

build site:
  image: node
  stage: build
  script:
    - npm ci --progress=false
    - npm run-script build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

eslint:
  stage: lint
  script:
    - npm i eslint
    - npm run-script lint

prettier:
  stage: lint
  script:
    - npm i prettier
    - npm run-script prettier

testing:
  stage: test
  script:
    - npm i
    - npm run test a
